### ISSUE TITLE
Failing with Vercel Build Process

### ISSUE THREAD

**Issue by calendee** [streamich/react-embed#340]
Hello,

Thanks so much for the great library!

I'm trying to using it in a Next.js app hosted on Vercel (formerly Zeit). When I run it locally, the `<Embed .../>` works just fine.

**Sample Usage**:

```
import Embed from "react-embed";

const Fallback = () => {
  return <div>...</div>
}

export default function publishedWorks() {
  const samples = [
    {
      id: 1,
      title: "Title 1",
      description: "Description 1",
      src: "https://youtu.be/soICQ3B2kEk",
    },
    {
      id: 2,
      title: "Title 2",
      description: "Description 2",
      src: "https://youtu.be/soICQ3B2kEk",
    },
  ];


  return (
    <section>
        <ul>
          {samples.map((sample) => (
            <li >
              <div>
                <div>
                  <Embed url={sample.src} fallback={Fallback}/>
                </div>
                <div className="p-4">
                  <h3>
                    {sample.title}
                  </h3>
                  <p>
                    {sample.description}
                  </p>
                </div>
              </div>
            </li>
          ))}
        </ul>
    </section>
  );
}
```

However, when I try to build using `next build`, I get the following:

```
> yarn build
yarn run v1.22.4
warning package.json: No license field
warning ../../../package.json: No license field
$ next build
[ info ]  Loaded env from .env
Creating an optimized production build

Compiled successfully.

Automatically optimizing pages ...
Error occurred prerendering page "/". Read more: https://err.sh/next.js/prerender-error:
[object Promise]

> Build error occurred
Error: Export encountered errors
    at _default (/Users/jn/Documents/Apps/noel-voice/node_modules/next/dist/export/index.js:19:1086)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async build (/Users/jn/Documents/Apps/noel-voice/node_modules/next/dist/build/index.js:36:218)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Next pre-renders pages for server side generation.  Something in the `react-embed` is causing it to fail.

Any ideas how to proceed?

**Comment by szepgergo** [comment]
Hello, I had the same problem. As a workaround I used `next/dynamic` import:
```
import dynamic from "next/dynamic";
const Embed = dynamic(() => import('react-embed'), {ssr: false});
```
